src/ShipFit/ShipFit.module.css
Now instead, they are a bit trapezium, and the outer border is a bit rounded. Additionally, slots are a bit darker to stand out better.
=> fix: slots layout look odd as they are full rectangles

.storybook/fits.ts, package.json, src/DogmaEngineProvider/DogmaEngineProvider.tsx, src/EveDataProvider/EveDataProvider.tsx
For this the dataset is modified to add effects and modifier. Additionally, some bugs in dogma-engine resulted in wrong numbers, so we bump that while at it.
=> feat: calculate velocity boost for AB / MWD correctly

src/EveDataProvider/EveDataProvider.tsx, src/EveDataProvider/esf_pb2.js, src/EveDataProvider/protobuf.js
content-length is not set by Cloudflare when content-encoding is used. So no longer depend on content-length, and just read till the end of the file.
=> fix: datafiles don't load when content-encoding is used

src/ShipAttribute/ShipAttribute.stories.tsx
The name changed a while ago from cpuUsage to cpuUsed.
=> fix: ShipAttribute storybook uses invalid attribute-name

src/ShipFit/FitLink.tsx
It does, as we only target browser, but okay, we will add a guard.
=> fix: NextJS warns that "window" doesn't exist

src/ShipFit/FitLink.tsx
This is because linkText is different on server (no "window") and client. Fix that by using a React hook.
=> fix: NextJS errors on difference between server-render and client-render

src/ShipFit/ShipFit.module.css
The new "share-link" had a z-index that was too high, making it capture all the clicks.
=> fix: unable to toggle modules

package.json, src/EsiCharacterSelection/EsiCharacterSelection.module.css, src/EsiCharacterSelection/EsiCharacterSelection.stories.tsx, src/EsiCharacterSelection/EsiCharacterSelection.tsx, src/EsiCharacterSelection/index.ts, src/EsiProvider/EsiAccessToken.tsx, src/EsiProvider/EsiProvider.stories.tsx, src/EsiProvider/EsiProvider.tsx, src/EsiProvider/EsiSkills.tsx, src/EsiProvider/index.ts, src/index.ts
This can track multiple characters, and tries to make as few as possible ESI calls.
In the localstorage, we keep track of all the characters and their refresh-tokens.
Access-tokens and skills are not stored in the localstorage, which means that every reload, this information is fetched from ESI again.
=> feat: ability to load characters and their skills from ESI

src/ShipFit/ShipFit.tsx, src/ShipSnapshotProvider/ShipSnapshotProvider.tsx, src/ShipSnapshotProvider/index.ts
More than only ShipFit needs it in the future, so by moving it closer to the calculation makes it easier for other places to use it again.
=> chore: calculate available slots in ShipSnapshotProvider

.storybook/main.ts
This also applies `prettier` formatting on the file, as it seemed to disagree with some lines.
Note: as per [documentation](https://storybook.js.org/docs/configure/telemetry), there is one `boot` event that is sent before this config it set. The alternative is to force the `STORYBOOK_DISABLE_TELEMETRY` env var, but that seems a bit much.
=> chore(storybook): Disable telemetry

src/ShipAttribute/ShipAttribute.tsx, src/ShipStatistics/ShipStatistics.tsx
- HP is always floor().
- Resistance is ceil(), sometimes. 10.01 becomes 10, but 10.1 becomes 11.
- Rest seems to be rounding.
=> fix: round statistics up/down correctly

src/CalculationDetail/CalculationDetail.stories.tsx, src/DroneBay/DroneBay.stories.tsx, src/EsiCharacterSelection/EsiCharacterSelection.stories.tsx, src/EsiProvider/EsiProvider.stories.tsx, src/EsiProvider/EsiProvider.tsx, src/EveShipFitLink/EveShipFitLink.stories.tsx, src/EveShipFitLink/EveShipFitLink.tsx, src/FitButtonBar/FitButtonBar.stories.tsx, src/FitButtonBar/RenameButton.tsx, src/FitButtonBar/SaveButton.tsx, src/FormatAsEft/FormatAsEft.stories.tsx, src/FormatAsEft/FormatAsEft.tsx, src/HardwareListing/HardwareListing.stories.tsx, src/HullListing/HullListing.stories.tsx, src/HullListing/HullListing.tsx, src/ShipAttribute/ShipAttribute.stories.tsx, src/ShipFit/Hull.tsx, src/ShipFit/ShipFit.stories.tsx, src/ShipFitExtended/ShipFitExtended.stories.tsx, src/ShipFitExtended/ShipFitExtended.tsx, src/ShipSnapshotProvider/ShipSnapshotProvider.stories.tsx, src/ShipSnapshotProvider/ShipSnapshotProvider.tsx, src/ShipStatistics/ShipStatistics.stories.tsx, src/TreeListing/TreeListing.stories.tsx
This makes EsiProvider dependant on ShipSnapshotProvider, but also avoids pages having to store skills themselves.
This is an alternative to #80.
Closes #80.
=> refactor: move skills storage inside ShipSnapshotProvider

src/DogmaEngineProvider/DogmaEngineProvider.tsx
React in StrictMode should run effect -> teardown -> effect, but for some reason it never does the second "effect" in time. In result, the dogma-engine is marked as loaded, but it really isn't.
Setting the dogma-engine as unloaded also doesn't work, as that signal arrives after the dogma-engine is used.
=> chore: remove teardown of window functions

src/FormatEftToEsi/FormatEftToEsi.tsx
It is most likely something in the cargohold.
=> fix: skip EFT entries that don't have effects/attributes

src/FormatEftToEsi/FormatEftToEsi.tsx
It is not ideal, but not importing anything isn't either.
=> fix: skip unknown items in EFT fits

README.md, package.json
You don't actually care what software does the formatting. Just that it gets done.
=> chore: rename "npm run prettier" to "npm run format"

src/components/HardwareListing/HardwareListing.tsx, src/components/ShipFit/Slot.tsx, src/components/TreeListing/TreeListing.tsx, src/providers/ShipSnapshotProvider/ShipSnapshotProvider.tsx
Fixes https://github.com/EVEShipFit/roadmap/issues/46
New Features: 
1. Added an ability to drag fitted items around: swap them or move an item to an empty slot. Added a special handling for fitted items with charges.
2. Added an ability to drag an item from Hardware to an individual fit slot. A support for dragging charges from the charges tab was not added in this pull-request.
Drag and drop feature is powered by a native [HTML Drag and Drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API).
There is a problem with the drag item image in case if user drags an item from the Hardware list for the first time. HTML Drag and Drop API supports a way to set an image like this:
```js
let img = new Image();
img.src = …
```
=> feat: ability to drag and drop items

src/hooks/ImportEveShipFitHash/DecodeEsfFitV1.tsx
They did have drones and cargo stored, so process them correctly.
During the time `v1` was used, drones and cargo weren't dealt with. So I was under the assumption they also weren't stored in the hash.
I was wrong.
Luckily, `v1` never existed after making EVEShip.fit public, so there is little impact.
=> fix: unbreak "fit:v1" links

src/components/HardwareListing/HardwareListing.tsx
When you have no low-slots, show no low-slot modules. And some rigs also have canFitShipNNN constraints.
=> fix: further restrict modules when hull restriction is enabled

.storybook/fits.ts, src/components/CargoBay/CargoBay.module.css, src/components/CargoBay/CargoBay.stories.tsx, src/components/CargoBay/CargoBay.tsx, src/components/CargoBay/index.ts, src/components/ShipAttribute/ShipAttribute.tsx, src/components/ShipFitExtended/ShipFitExtended.module.css, src/components/ShipFitExtended/ShipFitExtended.tsx, src/hooks/ExportEft/ExportEft.tsx, src/hooks/ImportEft/ImportEft.tsx, src/index.ts, src/providers/FitManagerProvider/FitManagerProvider.tsx, src/providers/StatisticsProvider/StatisticsProvider.tsx
Fixes https://github.com/EVEShipFit/roadmap/issues/60.
- You can view the cargohold (by clicking on it). Volume is also calculated.
- You can import/export of cargo, for all types (ESI, EFT, ..).
- You can drag items onto the cargohold to add them.
- You can drag items from the cargohold to fit them.
- You can remove items from the cargohold.
=> feat: import/show/change cargobay

src/components/ShipFit/ShipFit.tsx, src/components/ShipFit/Slot.tsx
This prevents the user from changing the fit.
=> feat: ability to set ShipFit in read-only mode

src/hooks/ExportEveShipFit/ExportEveShipFit.tsx
Uint8Array can no longer be cast to number[]. So do it manually.
=> fix: error during build step with newer rollup
